spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
  application:
    name: service-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
server:
  port: 8001
eureka:
  client.serviceUrl.defaultZone: http://localhost:8000/eureka/
  instance.instance-id: ${spring.application.name}:${server.port}
management:
  security: 
    enabled: false
       