server:
  port: 8004
spring:
  application:
    name: service-zipkin
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/