spring:
  zipkin:
    base-url: http://localhost:8004
  sleuth:
    sampler:
      percentage: 1.0
  # 开启消息跟踪
  cloud.bus.trace.enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
  application:
    name: service-person
server:
  port: 8002
# 刷新时，关闭安全验证
management.security.enabled: false
eureka.instance.instance-id: ${spring.application.name}:${server.port}